import { CommonModule } from '@angular/common';
import { purchaseOrderLineIdentity } from './purchase-order.utils';
import { Component, OnInit } from '@angular/core';
import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button'; import { MatCheckboxModule } from '@angular/material/checkbox'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginatorModule, PageEvent } from '@angular/material/paginator'; import { MatSelectModule } from '@angular/material/select'; import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { PurchaseOrder, PurchaseProductCandidate } from '../../interfaces/purchase-order'; import { Supplier } from '../../interfaces/supplier'; import { ProductSaleConfiguration } from '../../interfaces/inventory'; import { PurchaseOrderService } from '../../services/purchase-order.service'; import { SupplierService } from '../../services/supplier.service'; import { InventoryService } from '../../services/inventory.service';

interface SelectedPurchaseProduct { clientId:string; product: PurchaseProductCandidate; quantity: number; observation: string; config:ProductSaleConfiguration|null; presentationId:number|null; variantId:number|null; }
@Component({ selector:'app-purchase-order-form', standalone:true, imports:[CommonModule,FormsModule,ReactiveFormsModule,RouterLink,MatButtonModule,MatCheckboxModule,MatFormFieldModule,MatIconModule,MatInputModule,MatPaginatorModule,MatSelectModule,MatSlideToggleModule], templateUrl:'./purchase-order-form.component.html', styleUrl:'./purchase-orders.css' })
export class PurchaseOrderFormComponent implements OnInit {
  readonly form = this.fb.group({ providerId:[null as number|null,Validators.required], observation:[''] });
  suppliers:Supplier[]=[]; products:PurchaseProductCandidate[]=[]; selected=new Map<string,SelectedPurchaseProduct>(); loading=false; saving=false; lowStockOnly=true; search=''; page=0; size=10; total=0; editId:number|null=null; private nextLineId=1;
  constructor(private fb:FormBuilder,private api:PurchaseOrderService,private supplierApi:SupplierService,private inventoryApi:InventoryService,private route:ActivatedRoute,private router:Router,private toastr:ToastrService){}
  ngOnInit():void{this.supplierApi.getAllSuppliers().subscribe({next:s=>this.suppliers=s});const id=Number(this.route.snapshot.paramMap.get('id'));if(Number.isFinite(id)&&id>0){this.editId=id;this.loadDraft(id);}}
  providerChanged():void{this.selected.clear();this.page=0;this.loadProducts();}
  loadProducts():void{const providerId=this.form.controls.providerId.value;if(!providerId){this.products=[];return;}this.loading=true;const filters={providerId,productSearch:this.search,lowStockOnly:this.lowStockOnly,page:this.page,size:this.size,sort:'name,asc'};this.api.getProducts(filters).subscribe({next:r=>{this.products=r.contenido;this.total=r.totalElementos;this.loading=false;},error:e=>{this.loading=false;this.error(e);}});}
  loadDraft(id:number):void{this.loading=true;this.api.getPurchaseOrderById(id).subscribe({next:o=>{if(o.status!=='DRAFT'){this.toastr.warning('Solo se pueden editar pedidos en borrador.');this.router.navigate(['/dashboard/purchase-orders',id]);return;}this.form.patchValue({providerId:o.provider.id,observation:o.observation});this.loadProducts();o.details.forEach(d=>{const product:PurchaseProductCandidate={productId:d.productId,name:d.productName,code:d.code,barCode:d.barCode,providerId:o.provider.id,providerName:o.provider.name,productSupplierId:d.productSupplierId!,supplierProductCode:d.supplierProductCode,currentStock:d.stockAtOrderTime,minimumStock:0,suggestedQuantity:d.requestedQuantity,estimatedUnitCost:d.estimatedUnitCost,variantStockManaged:d.variantId!=null,lowStock:false};const item:SelectedPurchaseProduct={clientId:`detail-${d.id}`,product,quantity:d.requestedQuantity,observation:d.observation,config:null,presentationId:d.presentationId,variantId:d.variantId};this.selected.set(item.clientId,item);this.loadConfiguration(item);});},error:e=>{this.loading=false;this.error(e);}});}
  toggle(p:PurchaseProductCandidate,checked:boolean):void{if(checked&&!this.isSelected(p.productId))this.addLine(p);if(!checked)this.selectedItems.filter(i=>i.product.productId===p.productId).forEach(i=>this.selected.delete(i.clientId));}
  addLine(p:PurchaseProductCandidate):void{const clientId=`new-${this.nextLineId++}`;const item:SelectedPurchaseProduct={clientId,product:p,quantity:Math.max(0.000001,p.suggestedQuantity||1),observation:'',config:null,presentationId:null,variantId:null};this.selected.set(clientId,item);this.loadConfiguration(item);}
  removeLine(clientId:string):void{this.selected.delete(clientId);}
  isSelected(id:number):boolean{return this.selectedItems.some(i=>i.product.productId===id);} item(id:number):SelectedPurchaseProduct|undefined{return this.selectedItems.find(i=>i.product.productId===id);} private selectedItem(id:string|number):SelectedPurchaseProduct|undefined{return typeof id==='string'?this.selected.get(id):this.item(id);} updateQuantity(id:string|number,value:string):void{const i=this.selectedItem(id),q=Number(value);if(i&&Number.isFinite(q)&&q>0)i.quantity=q;} updateObservation(id:string|number,value:string):void{const i=this.selectedItem(id);if(i)i.observation=value;}
  updatePresentation(id:string|number,value:number|null):void{const i=this.selectedItem(id);if(i)i.presentationId=value;}
  updateVariant(id:string|number,value:number|null):void{const i=this.selectedItem(id);if(i)i.variantId=value;}
  pageChanged(e:PageEvent):void{this.page=e.pageIndex;this.size=e.pageSize;this.loadProducts();} filtersChanged():void{this.page=0;this.loadProducts();}
  get selectedItems():SelectedPurchaseProduct[]{return [...this.selected.values()];} get totalUnits():number{return this.selectedItems.reduce((s,i)=>s+i.quantity,0);} get estimatedTotal():number{return Math.round(this.selectedItems.reduce((s,i)=>s+i.quantity*i.product.estimatedUnitCost,0)*100)/100;}
  save():void{if(this.form.invalid||!this.selected.size||this.saving){this.form.markAllAsTouched();this.toastr.warning('Seleccioná un proveedor y al menos un producto.');return;}if(this.selectedItems.some(i=>i.product.variantStockManaged&&!i.variantId)){this.toastr.warning('Seleccioná una variante para cada producto que administra variantes.');return;}const identities=this.selectedItems.map(i=>purchaseOrderLineIdentity({productId:i.product.productId,variantId:i.variantId,presentationId:i.presentationId}));if(new Set(identities).size!==identities.length){this.toastr.warning('No se puede repetir la misma combinación de producto, variante y presentación.');return;}if(!confirm(`¿Guardar pedido con ${this.selected.size} líneas?`))return;const providerId=this.form.controls.providerId.value!;const request={providerId,observation:this.form.controls.observation.value||'',details:this.selectedItems.map(i=>({productId:i.product.productId,productSupplierId:i.product.productSupplierId,presentationId:i.presentationId,variantId:i.variantId,requestedQuantity:i.quantity,observation:i.observation}))};this.saving=true;const operation=this.editId?this.api.updatePurchaseOrder(this.editId,request):this.api.createPurchaseOrder(request);operation.subscribe({next:o=>{this.saving=false;this.toastr.success(this.editId?'Borrador actualizado.':'Pedido guardado como borrador.');this.router.navigate(['/dashboard/purchase-orders',o.id]);},error:e=>{this.saving=false;this.error(e);}});}
  private loadConfiguration(item:SelectedPurchaseProduct):void{this.inventoryApi.getSaleConfiguration(item.product.productId).subscribe({next:c=>item.config=c,error:()=>item.config=null});}
  private error(error:unknown):void{const e=error as{error?:{message?:string}};this.toastr.error(e.error?.message||'No se pudo completar la operación.');}
}
