import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button'; import { MatCheckboxModule } from '@angular/material/checkbox'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginatorModule, PageEvent } from '@angular/material/paginator'; import { MatSelectModule } from '@angular/material/select'; import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { PurchaseOrder, PurchaseProductCandidate } from '../../interfaces/purchase-order'; import { Supplier } from '../../interfaces/supplier'; import { PurchaseOrderService } from '../../services/purchase-order.service'; import { SupplierService } from '../../services/supplier.service';

interface SelectedPurchaseProduct { product: PurchaseProductCandidate; quantity: number; observation: string; }
@Component({ selector:'app-purchase-order-form', standalone:true, imports:[CommonModule,FormsModule,ReactiveFormsModule,RouterLink,MatButtonModule,MatCheckboxModule,MatFormFieldModule,MatIconModule,MatInputModule,MatPaginatorModule,MatSelectModule,MatSlideToggleModule], templateUrl:'./purchase-order-form.component.html', styleUrl:'./purchase-orders.css' })
export class PurchaseOrderFormComponent implements OnInit {
  readonly form = this.fb.group({ providerId:[null as number|null,Validators.required], observation:[''] });
  suppliers:Supplier[]=[]; products:PurchaseProductCandidate[]=[]; selected=new Map<number,SelectedPurchaseProduct>(); loading=false; saving=false; lowStockOnly=true; search=''; page=0; size=10; total=0; editId:number|null=null;
  constructor(private fb:FormBuilder,private api:PurchaseOrderService,private supplierApi:SupplierService,private route:ActivatedRoute,private router:Router,private toastr:ToastrService){}
  ngOnInit():void{this.supplierApi.getAllSuppliers().subscribe({next:s=>this.suppliers=s});const id=Number(this.route.snapshot.paramMap.get('id'));if(Number.isFinite(id)&&id>0){this.editId=id;this.loadDraft(id);}}
  providerChanged():void{this.selected.clear();this.page=0;this.loadProducts();}
  loadProducts():void{const providerId=this.form.controls.providerId.value;if(!providerId){this.products=[];return;}this.loading=true;const filters={providerId,productSearch:this.search,lowStockOnly:this.lowStockOnly,page:this.page,size:this.size,sort:'name,asc'};this.api.getProducts(filters).subscribe({next:r=>{this.products=r.contenido;this.total=r.totalElementos;this.loading=false;},error:e=>{this.loading=false;this.error(e);}});}
  loadDraft(id:number):void{this.loading=true;this.api.getPurchaseOrderById(id).subscribe({next:o=>{if(o.status!=='DRAFT'){this.toastr.warning('Solo se pueden editar pedidos en borrador.');this.router.navigate(['/dashboard/purchase-orders',id]);return;}this.form.patchValue({providerId:o.provider.id,observation:o.observation});this.loadProducts();o.details.forEach(d=>this.selected.set(d.productId,{product:{productId:d.productId,name:d.productName,code:d.code,barCode:d.barCode,providerId:o.provider.id,providerName:o.provider.name,currentStock:d.stockAtOrderTime,minimumStock:0,suggestedQuantity:d.requestedQuantity,estimatedUnitCost:d.estimatedUnitCost,lowStock:false},quantity:d.requestedQuantity,observation:d.observation}));},error:e=>{this.loading=false;this.error(e);}});}
  toggle(p:PurchaseProductCandidate,checked:boolean):void{if(checked&&!this.selected.has(p.productId))this.selected.set(p.productId,{product:p,quantity:Math.max(1,Math.trunc(p.suggestedQuantity||1)),observation:''});if(!checked)this.selected.delete(p.productId);}
  isSelected(id:number):boolean{return this.selected.has(id);} item(id:number):SelectedPurchaseProduct|undefined{return this.selected.get(id);} updateQuantity(id:number,value:string):void{const i=this.selected.get(id);if(i)i.quantity=Math.max(1,Math.trunc(Number(value)||1));} updateObservation(id:number,value:string):void{const i=this.selected.get(id);if(i)i.observation=value;}
  pageChanged(e:PageEvent):void{this.page=e.pageIndex;this.size=e.pageSize;this.loadProducts();} filtersChanged():void{this.page=0;this.loadProducts();}
  get selectedItems():SelectedPurchaseProduct[]{return [...this.selected.values()];} get totalUnits():number{return this.selectedItems.reduce((s,i)=>s+i.quantity,0);} get estimatedTotal():number{return Math.round(this.selectedItems.reduce((s,i)=>s+i.quantity*i.product.estimatedUnitCost,0)*100)/100;}
  save():void{if(this.form.invalid||!this.selected.size||this.saving){this.form.markAllAsTouched();this.toastr.warning('Seleccioná un proveedor y al menos un producto.');return;}if(!confirm(`¿Guardar pedido con ${this.selected.size} productos?`))return;const providerId=this.form.controls.providerId.value!;const request={providerId,observation:this.form.controls.observation.value||'',details:this.selectedItems.map(i=>({productId:i.product.productId,requestedQuantity:i.quantity,observation:i.observation}))};this.saving=true;const operation=this.editId?this.api.updatePurchaseOrder(this.editId,request):this.api.createPurchaseOrder(request);operation.subscribe({next:o=>{this.saving=false;this.toastr.success(this.editId?'Borrador actualizado.':'Pedido guardado como borrador.');this.router.navigate(['/dashboard/purchase-orders',o.id]);},error:e=>{this.saving=false;this.error(e);}});}
  private error(error:unknown):void{const e=error as{error?:{message?:string}};this.toastr.error(e.error?.message||'No se pudo completar la operación.');}
}
