export type CloudOrderStatus='PENDING_REVIEW'|'REVIEW_REQUIRED'|'ACCEPTED'|'REJECTED'|'CONVERTED_TO_SALE'|'PREPARING'|'READY'|'OUT_FOR_DELIVERY'|'DELIVERED'|'READY_FOR_PICKUP'|'PICKED_UP'|'CANCELLED'|'ERROR';
export type CloudResultStatus='PENDING'|'SYNCED'|'ERROR';
export interface CloudOrderSummary{id:number;cloudOrderNumber:string;cloudCreatedAt:string;customerName:string;customerPhone:string;total:number;paymentMethod:string;status:CloudOrderStatus;hasProblems:boolean;ticketId?:number;cloudResultStatus:CloudResultStatus}
export interface CloudOrderGastronomySelection{cloudGroupId?:number|null;cloudOptionId?:number|null;groupName:string;optionName:string;priceAdjustment:number}
export interface CloudOrderItem{id:number;externalProductId:string;snapshotName:string;barcode?:string;quantity:number;orderUnitPrice:number;subtotal:number;localProductId?:number;localProductName?:string;currentPrice?:number;currentStock?:number;resolutionStatus:string;variantSelectionRequired:boolean;resolvedVariantId?:number;resolvedVariantName?:string;gastronomySelections?:CloudOrderGastronomySelection[]}
export interface CloudOrderDetail extends CloudOrderSummary{cloudOrderId:string;receivedAt:string;customerEmail?:string;customerDocument?:string;fulfillmentType?:'PICKUP'|'DELIVERY';logisticsStatus?:'PREPARING'|'READY'|'OUT_FOR_DELIVERY'|'DELIVERED'|'READY_FOR_PICKUP'|'PICKED_UP'|null;deliveryAddress?:string;deliveryCity?:string;deliveryReference?:string;deliveryZoneId?:number|null;deliveryZoneName?:string|null;shippingCost?:number|null;latitude:number|null;longitude:number|null;locationAccuracy:number|null;locationSource:string|null;subtotal:number;rejectionReason?:string;rejectionMessage?:string;localClientId?:number;items:CloudOrderItem[];currentAccount?:{clientId:number;clientName:string;enabled:boolean;debt:number;limit:number;available:number;orderAmount:number};cloudResultLastAttemptAt?:string;cloudResultAttempts:number;cloudResultLastError?:string}
export interface CloudOrderPage{contenido:CloudOrderSummary[];pagina:number;tamanio:number;totalElementos:number;totalPaginas:number}
export interface CloudVariant{id:number;name:string;sku:string;barcode?:string;stock:number;active:boolean}
export interface ClientOption{id:number;name:string;document:string;currentAccountEnabled:boolean}
export interface ClientOptionPage{contenido:ClientOption[];pagina:number;tamanio:number;totalElementos:number;totalPaginas:number}
