export interface ReportPage<T> { contenido: T[]; pagina: number; tamanio: number; totalElementos: number; totalPaginas: number; }
export interface SupplierReportRef { productSupplierId: number; providerId: number; providerName: string; lastPurchasePrice: number | null; preferred: boolean; }
export interface SupplierCostComparison { productSupplierId: number; providerId: number; providerName: string; supplierProductCode: string | null; supplierBarcode: string | null; purchasePrice: number | null; lastPurchasePrice: number | null; preferred: boolean; active: boolean; differenceVsBest: number | null; differencePercentageVsBest: number | null; }
export interface ProductSupplierComparison { productId: number; productName: string; productBarcode: string; generalCost: number | null; preferredSupplierId: number | null; preferredSupplierName: string | null; bestSupplierId: number | null; bestSupplierName: string | null; bestLastPurchasePrice: number | null; suppliers: SupplierCostComparison[]; }
export interface ProductComparisonSummary { productId: number; productName: string; generalCost: number | null; bestSupplier: SupplierReportRef | null; preferredSupplier: SupplierReportRef | null; supplierCount: number; comparableSupplierCount: number; }
export interface CostHistoryItem { invoiceId: number; invoiceNumber: string; invoiceDate: string; providerId: number; providerName: string; productId: number; productName: string; supplierProductCodeSnapshot: string | null; quantity: number; baseQuantity: number; precioLista: number; precioNeto: number; precioTotal: number; previousNetPrice: number | null; priceDifference: number | null; priceDifferencePercentage: number | null; }
export interface ProviderPurchaseSummary { providerId: number; providerName: string; invoiceCount: number; totalPurchased: number; averageInvoiceAmount: number; lastPurchaseDate: string | null; distinctProductCount: number; }
export interface ProviderInvoiceReport { invoiceId: number; invoiceNumber: string; invoiceDate: string; total: number; lineCount: number; }
export interface CostAlert { productId: number; productName: string; generalCost: number | null; alertTypes: string[]; activeSupplierCount: number; comparableSupplierCount: number; preferredSupplier: SupplierReportRef | null; bestSupplier: SupplierReportRef | null; }
export interface SavingsRequestItem { productId: number; quantity: number; }
export interface SavingsItem { productId: number; productName: string; quantity: number; currentReferenceCost: number | null; currentReferenceProvider: SupplierReportRef | null; bestSupplierId: number | null; bestSupplierName: string | null; bestUnitCost: number | null; currentEstimatedTotal: number | null; bestEstimatedTotal: number | null; potentialSavings: number | null; potentialSavingsPercentage: number | null; }
export interface SavingsResponse { items: SavingsItem[]; totalCurrentEstimated: number | null; totalBestEstimated: number | null; totalPotentialSavings: number | null; }
export interface ProviderProductReport { productSupplierId: number; productId: number; productName: string; productBarcode: string; supplierProductCode: string | null; supplierBarcode: string | null; purchasePrice: number | null; lastPurchasePrice: number | null; preferred: boolean; generalProductCost: number | null; }
