import { CommonModule } from '@angular/common'; import { Component, OnInit } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { MatButtonModule } from '@angular/material/button'; import { MatIconModule } from '@angular/material/icon'; import { MatTabsModule } from '@angular/material/tabs'; import { ToastrService } from 'ngx-toastr'; import { Client } from '../../interfaces/Client'; import { Empleado, EstadoCuentaEmpleado, LiquidacionSueldo, PagoEmpleado } from '../../interfaces/empleado'; import { ClientService } from '../../services/client.service'; import { EmpleadoService } from '../../services/empleado.service';
@Component({selector:'app-empleados',standalone:true,imports:[CommonModule,FormsModule,MatButtonModule,MatIconModule,MatTabsModule],templateUrl:'./empleados.component.html',styleUrl:'./empleados.component.css'})
export class EmpleadosComponent implements OnInit { empleados:Empleado[]=[]; clientes:Client[]=[]; seleccionado?:Empleado; estado?:EstadoCuentaEmpleado; liquidaciones:LiquidacionSueldo[]=[]; movimientos:any[]=[]; editando?:Empleado; pagos:PagoEmpleado[]=[{medioPago:'EFECTIVO',monto:0}]; adelanto={monto:0,medioPago:'EFECTIVO',referencia:'',fecha:new Date().toISOString().slice(0,10),observacion:''}; periodo={desde:'',hasta:'',observacion:''}; reporte={desde:'',hasta:''}; form:any={nombre:'',apellido:'',dni:'',sueldo:0,puesto:'',fechaIngreso:new Date().toISOString().slice(0,10),activo:true,tipoContrato:'FULL_TIME',frecuenciaPago:'MENSUAL',clienteId:null}; medios=['EFECTIVO','TRANSFERENCIA','DEBITO','CREDITO','MERCADO_PAGO','CHEQUE','OTRO'];
constructor(private api:EmpleadoService,private clientesApi:ClientService,private toast:ToastrService){} ngOnInit(){this.cargar();this.clientesApi.getClients().subscribe(x=>this.clientes=x);}
cargar(){this.api.getAll().subscribe({next:x=>this.empleados=x,error:()=>this.toast.error('No se pudieron cargar empleados')});} nuevo(){this.editando=undefined;this.form={nombre:'',apellido:'',dni:'',sueldo:0,puesto:'',fechaIngreso:new Date().toISOString().slice(0,10),activo:true,tipoContrato:'FULL_TIME',frecuenciaPago:'MENSUAL',clienteId:null};} editar(e:Empleado){this.editando=e;this.form={...e};} guardar():void{if(!this.form.nombre||!this.form.apellido||!this.form.dni||this.form.sueldo<=0){this.toast.warning('Completá nombre, DNI y sueldo');return;}const op=this.editando?this.api.actualizar(this.editando.id,this.form):this.api.crear(this.form);op.subscribe({next:()=>{this.toast.success('Empleado guardado');this.nuevo();this.cargar();},error:e=>this.toast.error(e.error?.error||'No se pudo guardar')});}
seleccionar(e:Empleado){this.seleccionado=e;this.api.estadoCuenta(e.id).subscribe(x=>this.estado=x);this.api.liquidaciones(e.id).subscribe(x=>this.liquidaciones=x);this.api.movimientos(e.id).subscribe(x=>this.movimientos=x);} desactivar(e:Empleado){this.api.desactivar(e.id).subscribe(()=>{this.toast.success('Empleado desactivado');this.cargar();});}
registrarAdelanto(){if(!this.seleccionado||this.adelanto.monto<=0)return;this.api.adelanto(this.seleccionado.id,this.adelanto).subscribe({next:()=>{this.toast.success('Adelanto registrado');this.seleccionar(this.seleccionado!);},error:e=>this.toast.error(e.error?.error||'No se pudo registrar el adelanto')});} liquidar():void{if(!this.seleccionado||!this.periodo.desde||!this.periodo.hasta){this.toast.warning('Indicá el período');return;}this.api.crearLiquidacion(this.seleccionado.id,{periodoDesde:this.periodo.desde,periodoHasta:this.periodo.hasta,observacion:this.periodo.observacion}).subscribe({next:()=>{this.toast.success('Liquidación creada');this.seleccionar(this.seleccionado!);},error:e=>this.toast.error(e.error?.error||'No se pudo liquidar')});}
totalPagos(){return this.pagos.reduce((a,p)=>a+Number(p.monto||0),0)} pagar(l:LiquidacionSueldo):void{if(this.totalPagos()!==Number(l.netoAPagar)){this.toast.warning('Los pagos deben coincidir exactamente con el neto');return;}this.api.pagarLiquidacion(l.id,this.pagos).subscribe({next:()=>{this.toast.success('Sueldo pagado');this.pagos=[{medioPago:'EFECTIVO',monto:0}];this.seleccionar(this.seleccionado!);},error:e=>this.toast.error(e.error?.error||'No se pudo registrar el pago')});} descargar(){if(!this.reporte.desde||!this.reporte.hasta)return;this.api.reportePdf(this.reporte.desde,this.reporte.hasta).subscribe(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`nomina-${this.reporte.desde}-${this.reporte.hasta}.pdf`;a.click();URL.revokeObjectURL(u);});}
}
